name: Build and Deploy to Tomcat 10

on:
  push:
    branches:
      - master  # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build WAR file using Maven
        run: mvn clean package

      - name: Deploy WAR to Tomcat 10 via Manager
        env:
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
          TOMCAT_HOST: ${{ secrets.TOMCAT_HOST }}  # e.g., 192.168.1.100 or myserver.com
        run: |
          WAR_FILE=target/cdms-0.0.1-SNAPSHOT.war

          if [ ! -f "$WAR_FILE" ]; then
            echo "WAR file not found: $WAR_FILE"
            exit 1
          fi

          echo "Deploying WAR to Tomcat Manager..."
          curl -u "$TOMCAT_USER:$TOMCAT_PASSWORD" \
               -T "$WAR_FILE" \
               "http://$TOMCAT_HOST:8080/manager/text/deploy?path=/cdms&update=true"
